### ISSUE TITLE
Upcoming breakage due to set_output changes

### ISSUE THREAD

**Issue by iustin** [8c6794b6/hpc-codecov-action#2]
During a coverage run, I get these messages:

```
Writing JSON report to "./codecov.json"
Done
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

The above link says:

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

Would be good if this can be updated and fixed before the deadline - thanks!

**Comment by 8c6794b6** [comment]
Thank you for reporting the issue, fixed in the ``main`` and ``v2`` branches.

**Comment by iustin** [comment]
Thanks a lot!
